# KFOLD - DIGIT 

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

%matplotlib inline
warnings.filterwarnings('ignore')

from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [3]:
digits = load_digits()

### using logistic regression

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [32]:
log = LogisticRegression()
log.fit(X_train,y_train)
log.score(X_test,y_test)

0.9611111111111111

### Using svm

In [33]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9944444444444445

### Using RandomForest

In [34]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [35]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [36]:
#how the kfolds works
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [37]:
# building function to generate score of models
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [38]:
#testing the function
get_score(SVC(), X_train,X_test,y_train,y_test)

0.9944444444444445

In [39]:
from sklearn.model_selection import StratifiedKFold #very similar to the normal Kfold only that it keeps distribion of attributes in consideration
folds = StratifiedKFold(n_splits=3)

In [40]:
score_log = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                            digits.target[train_index],digits.target[test_index]
    
    score_log.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    score_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))
    


In [41]:
score_log

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [42]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [43]:
score_rf

[0.9315525876460768, 0.9515859766277128, 0.9282136894824707]

In [44]:
np.array(score_log).mean()

0.9265442404006677

In [45]:
np.array(score_svm).mean()

0.9677239844184752

In [46]:
np.array(score_rf).mean()

0.9371174179187535

# USING THE IN-BUILT SCIKIT METHOD TO DO THE ABOVE

In [47]:
from sklearn.model_selection import cross_val_score

In [54]:
cross_val_score(LogisticRegression(),digits.data, digits.target, cv=3).mean()

0.9265442404006677

In [55]:
cross_val_score(SVC(),digits.data, digits.target, cv=3).mean()

0.9699499165275459

In [56]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target, cv=3).mean()

0.9410127991096271

Again we have the SVM performing better