# PROBLEM STATEMENT
Wonder what species of iris do this flowers belong to?

Let's try tp predict the species of the flowers using machine learning in python

In [1]:
import  numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

#setting random seed
np.random.seed(0)


In [12]:
iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [13]:
df['target'] = pd.DataFrame(iris.target, columns=['target'])

In [31]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [34]:
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target species  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [35]:
#Creating a train and test data
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target', 'species'],
      dtype='object')

In [46]:
x = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)']]
y = df['target']

In [47]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [48]:
# Creating a random forest classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)
# training the classifier
clf.fit(X_train,y_train)

RandomForestClassifier(n_jobs=2, random_state=0)

In [49]:
X_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
61                 5.9               3.0                4.2               1.5
92                 5.8               2.6                4.0               1.2
112                6.8               3.0                5.5               2.1
2                  4.7               3.2                1.3               0.2
141                6.9               3.1                5.1               2.3

In [50]:
y_train.head()

61     1
92     1
112    2
2      0
141    2
Name: target, dtype: int32

In [51]:
#applying the trained classifier to the test
y_predict = clf.predict(X_test)

In [52]:
y_predict

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [55]:
clf.predict_proba(X_test)[0:10]

array([[0.  , 0.01, 0.99],
       [0.  , 0.94, 0.06],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.01, 0.99],
       [1.  , 0.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 0.92, 0.08],
       [0.  , 1.  , 0.  ]])

In [67]:
pred_by_name = iris.target_names[y_predict]
pred = pred_by_name #prediction

In [68]:
#actual
actual = iris.target_names[y_test]

In [62]:
from sklearn import metrics

In [72]:
metrics.confusion_matrix(y_predict, y_test)

array([[13,  0,  0],
       [ 0, 15,  0],
       [ 0,  1,  9]], dtype=int64)

In [70]:
# creating a confusion matrix
pd.crosstab(actual, pred, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0          15          1
virginica               0           0          9

Number of accurate prediction is 37 with one miss

In [75]:
metrics.accuracy_score(y_test,y_predict)*100

97.36842105263158

the model accuracy is 97%

#### Testing out the model with new data

In [77]:
preds = iris.target_names[clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])]
preds

array(['setosa', 'setosa'], dtype='<U10')